language: php

dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

script:
  - phpize
  - ./configure
  - make EXTRA_CFLAGS='-coverage' EXTRA_LDFLAGS='-fprofile-arcs'
  - make test
  - gcov --object-directory=src/.libs src/collections_methods.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
